apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: deepseek-coder-template
  annotations:
    scenarios.ai.sap.com/name: deepseek-coder
    scenarios.ai.sap.com/description: DeepSeek Coder 1.3B Instruct Model
    executables.ai.sap.com/name: deepseek-coder
    executables.ai.sap.com/description: DeepSeek model FastAPI service
  labels:
    scenarios.ai.sap.com/id: deepseek-coder
    ai.sap.com/version: "1.0"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
      labels:
        ai.sap.com/resourcePlan: infer.l  # Large plan for GPU
    spec:
      predictor:
        imagePullSecrets:
          - name: default  # Use your Docker registry secret name
        containers:
          - name: kserve-container
            image: index.docker.io/ravivarmaiai/deepseek-coder:1.0
            ports:
              - containerPort: 8080
